SRC/CardScreen.tsx

- Added mvp design for CardScreen component

Added Card Screen Design

---

SRC/StackScreens/LoginScreen.tsx

Add the log in screen, only te design

add login screen

---

SRC/StackScreens/RegisterScreen.tsx

Added RegisterScreen to project

Added RegisterScreen

---

App.tsx
SRC/StackScreens/ProfileImage.tsx
SRC/Styles/TextStyles.ts
android/app/build.gradle

Created the design for the screen and the flatlist to render the images.
The array imgs contain all the images, thats why is too large, but it can be a external json.
.-Add a new styles in TextStyle.tsx

Add user profile image screen

---

App.tsx
SRC/StackNavigation/stackNavigation.tsx
package-lock.json
package.json

- Installed react-navigation
- Added MyStack to navigate through app
- Added NavigationContainer to App component
MyStack
App

Installed Stack Navigator and created stack

---

SRC/StackScreens/CardScreen.tsx
SRC/StackScreens/HomeScreen.tsx
SRC/StackScreens/LoginScreen.tsx
SRC/StackScreens/RegisterScreen.tsx

I made the props for the screen HomeScreen, CardScreen, Login and RegisterScreen

Define types and interfaces

---

App.tsx
SRC/Components/ImageComponent.tsx
SRC/StackNavigation/stackNavigation.tsx
SRC/StackScreens/LoginScreen.tsx
SRC/StackScreens/ProfileImage.tsx
SRC/StackScreens/ProfileImageScreen.tsx
yarn.lock

In this commit I implemented the functionalities so that when selecting a profile photo it is changed on the login screen and at the same time you see the navigation of the new screen to select the image and login
If applicable, include screenshots of the results or screenshots that help to see changes

Implementation of image change functionality

---

SRC/Components/PasswordInput.tsx
SRC/Components/ScreenButton.tsx
SRC/Styles/ButtonStyles.ts
SRC/Styles/TextInputStyles.ts

What did you implemented:
-PasswordInput component to reuse on log in and sign in screens
-ScrennButton with a text and function props to reuse on every screen

Added PasswordInput and ScreenButton components ready to use

---

App.tsx
src/Components/Button.tsx
src/Components/Input.tsx
src/Screens/LogIn.tsx
src/Screens/LogInFingerprint.tsx
src/Screens/SignUp.tsx

Created FormButton and FormInput component for the forms (login and sign up)
Created the design for FingerPrintLogin, Login and Sign up

add fingerprintLogin, Login and Sign up screens and components

---

src/Screens/DebitCardDetails.tsx
src/Screens/Home.tsx
src/Screens/TarjetaCredito.tsx
src/Screens/TarjetaDebito.tsx

- All screens are ready according to the design

Home, CardDetails, TarjetaCredito and TarjetaDebito creens finished

---

android/app/build.gradle
src/Components/Contacto.tsx
src/Components/InputDestinatario.tsx
src/Screens/AddContact.tsx
src/Screens/Destinatario.tsx
src/Screens/Transferir.tsx

Designing contact screens, adding contacts and transfers

Create the design for contacts, add contact and transfer screens 

---

App.tsx
package-lock.json
package.json
src/StackNavigation/MyStack.tsx
yarn.lock

- Created stackNavigation
- Added all screens to stack
- Styled header of each screen

Created stack navigation including header styles for esach screen

---

package-lock.json
package.json
src/Components/Button.tsx
src/Components/Input.tsx
src/Firebase/firebaseconfig.tsx
src/Screens/LogIn.tsx
src/Screens/SignUp.tsx
tsconfig.json
yarn.lock

.-Added the funcionality in log in/ sign up forms 
.-Added new configuration to firebaseConfig
.-Now can create users with email and password or google account 
.-The user uid is stored in rn async storage and can be accessed in other screens

Implementation of firebase and store of users in auth provider with email/password and google

---

src/Screens/Config.tsx
src/Screens/ConfigUser.tsx

Created the layouts of the Config and ConfigUser screens

Agregando los cambios en las pantallas Config.tsx y ConfigUser.tsx

---

package-lock.json
package.json
src/Components/Input.tsx
src/Screens/LogIn.tsx
src/Screens/SignUp.tsx
yarn.lock

log in/sign validations were implemented.
.-All the inputs must be filled
.-The email must be a valid string
.-The password can be hidden with the eye icon
.-Manage errors if firebase return an error code(This email alredy exist, or the password is incorrect)

Add validations in log in/sign up forms

---

src/Components/Contacto.tsx
src/Components/InputDestinatario.tsx
src/Firebase/db.tsx
src/Firebase/firebaseconfig.tsx
src/Screens/AddContact.tsx
src/Screens/SelectContact.tsx
src/Screens/Transferir.tsx

db.tsx:
.-Add function to get the document reference for the actual user
.-Add function to addContant in nested collection in user document
.-Add function to getContacts from the nested collection
ContactScreen
.-Now, the contacs are rendered by the information in firebase 
.-The screens now share the contact info
undefined is because I change the name for the value. From now, all the contacs must have the number

add db functions for contacs 

---

src/Firebase/db.tsx
src/Firebase/firebaseconfig.tsx
src/Screens/AddContact.tsx
src/Screens/LogIn.tsx
src/Screens/LogInFingerprint.tsx
src/Screens/SelectContact.tsx
src/Screens/SignUp.tsx
src/Screens/Transferir.tsx

Why did you implemented this:
- EThis was implemented so that users can have automatically a debit and credit cards in their accounts
Data is sent to data base with this structure
data sent to data base has this structure

Implemented functionality to create user's cards automatically when signed in

---

App.tsx
src/Screens/Home.tsx
src/Screens/LogIn.tsx
src/Screens/LogInFingerprint.tsx
src/Screens/SignUp.tsx

- Added a context for saving user info
- User info is displayed on Home screen when is logged in

Show user info on Home Screen

---

App.tsx
src/Components/Contacto.tsx
src/Components/MoveCard.tsx
src/Screens/Config.tsx
src/Screens/ConfigUser.tsx
src/Screens/CreditCardDetails.tsx
src/Screens/DebitCardDetails.tsx
src/Screens/Home.tsx
src/Screens/LogIn.tsx
src/Screens/LogInFingerprint.tsx
src/Screens/SelectContact.tsx
src/Screens/SignUp.tsx
src/Screens/TarjetaCredito.tsx
src/Screens/TarjetaDebito.tsx
src/Screens/Transferir.tsx
src/StackNavigation/MyStack.tsx

- La infomacion del usuairo se muestra en todas las pantallas
- Google signIn funciona correctamente en las pantallas LogIn, SignUp y logInFingerprint
- Se agrego cvv a las tarjetas
- se le dio formato a los saldos y numeros de tarjeta en las pantallas  
- los movimientos de tarjeta se muestran correctamente

Show user info on all screens

---

App.tsx
src/Components/Contacto.tsx
src/Firebase/db.tsx
src/Screens/SelectContact.tsx

-Add new format in db for the contacts
-Correction of Contact component

add corrections to add and getcontacts functions

---

src/Firebase/db.tsx
src/Screens/Transferir.tsx

.-Created 2 independent functions to complete the transaction 
.-Now, all the users can add new contacts
.-The transaction are parsed to numbers
If applicable, include screenshots of the results or screenshots that help to see changes
An user in firestore with 0 in his account
the transaction from another account 
Now the user have 100

added functions to transfer between cards

---

App.tsx
src/Components/ConfirmationModal.tsx
src/Components/Contacto.tsx
src/Components/InputDestinatario.tsx
src/Components/MoveCard.tsx
src/Firebase/db.tsx
src/Screens/AddContact.tsx
src/Screens/CreditCardDetails.tsx
src/Screens/DebitCardDetails.tsx
src/Screens/Home.tsx
src/Screens/LogIn.tsx
src/Screens/LogInFingerprint.tsx
src/Screens/Retirar.tsx
src/Screens/RetiroDetalles.tsx
src/Screens/SelectContact.tsx
src/Screens/SignUp.tsx
src/StackNavigation/MyStack.tsx

- Users can withdraw money in app
- Withdraw movement appears on real time
- Log in now subscribes to onSnapshot to update data in real time
- Retirar screens are completed
Here you can see the design and how data changes when user make a withdraw

Design of withdraw money screen working now

---

src/Screens/TarjetaDebito.tsx

Redesign of the card screen with respect to the one established in figma

redesign of the card screen 

---

src/Components/Button.tsx
src/Components/InputDestinatario.tsx
src/Screens/AddContact.tsx
src/Screens/Transferir.tsx

In this commit, validations for fields on the transfer and add contact screens are implemented. If the fields are empty, the button is disabled, and if the content is incorrect or not of the required length, an alert message is displayed.

Add validation in add contact and transfer forms

---

src/Firebase/db.tsx
src/Screens/Config.tsx
src/Screens/LogIn.tsx
src/Screens/LogInFingerprint.tsx
src/Screens/Transferir.tsx

-When user makes a transference movement appears on user account and destination user account too

Increase and discount movements for a transference

---

App.tsx
src/Components/MoveCard.tsx
src/Components/Movement.tsx
src/Firebase/db.tsx
src/Screens/History.tsx
src/Screens/Home.tsx
src/Screens/SignUp.tsx
src/Screens/TarjetaDebito.tsx
src/Screens/Transferir.tsx
src/StackNavigation/MyStack.tsx

.-Design for the screen
.-Fetch data from the user in firebase 
.-The data was organized to be optimal rendered 
.-The movements were organized by dates
.-The movements are differentiated by negative or positive

add the functionality and the design for  history screen

---

src/Components/Contacto.tsx
src/Screens/AddContact.tsx
src/Screens/SelectContact.tsx
src/Screens/Transferir.tsx

Redesign of contacts, add contacts and transfer. according to figma

Redesign of contacts, add contacts and transfer

---

src/Screens/Config.tsx
src/Screens/CreditCardDetails.tsx
src/Screens/DebitCardDetails.tsx
src/StackNavigation/MyStack.tsx

- Changed style of Credit card, debit card, and cofig screens

Design improvement part 3

---

package-lock.json
package.json
src/Components/Movement.tsx
src/Screens/History.tsx
yarn.lock

.-Added calendar modal
.-Added button to open calendar
.-Added function to filter by date
-When the user select the dates and click  in button"filtrar" , the new list is rendered.

Add function to filter history by date 

---

android/app/src/main/AndroidManifest.xml
package-lock.json
package.json
src/Components/MapView.tsx
src/Screens/History.tsx
src/Screens/Retirar.tsx
yarn.lock

.-Installation of the following packages :
1.-react-native-maps
2.-react-native-getLocation
.-Creation of the main map component
.-Adjust the current location
.-Creation of the api key for google cloud platform

Maps Api implementation

---

src/Firebase/db.tsx
src/Screens/AddContact.tsx

In this issue, conflicts regarding the AddContact screen were resolved and validation was implemented to ensure that the account number being added is registered in the database.

Resolving conflicts for the AddContacts screen.

---

android/app/src/main/AndroidManifest.xml
package-lock.json
src/Components/MoveCard.tsx
src/Components/Movement.tsx
src/Firebase/db.tsx
src/Screens/AddContact.tsx
src/Screens/DebitCardDetails.tsx
src/Screens/History.tsx
src/Screens/LogIn.tsx
src/Screens/MisTarjetas.tsx
src/Screens/SelectContact.tsx
src/Screens/Transferir.tsx
src/StackNavigation/MyStack.tsx
yarn.lock

- Group dates for debit card screen
- minor style changes

Group dates from debit card screen

---

src/Components/Contacto.tsx
src/Components/InfoModal.tsx
src/Components/MoveCard.tsx
src/Components/Movement.tsx
src/Firebase/db.tsx
src/Screens/Config.tsx
src/Screens/DebitCardDetails.tsx
src/Screens/LogIn.tsx
src/Screens/MisTarjetas.tsx
src/Screens/Retirar.tsx
src/Screens/SelectContact.tsx
src/Screens/SignUp.tsx
src/Screens/VirtualCardDetails.tsx
src/StackNavigation/MyStack.tsx

- Added Virtual Card screen
- user can turn card on and off
- user can create a dynamic cvv for virtual card

Sprint 9 issue#95 add virtual card

---

src/Screens/DatosPersonales.tsx
src/Screens/PasswordRe.tsx
src/Screens/SignUp.tsx
src/StackNavigation/MyStack.tsx

reset password and screen desing

Add functions and design for buttons on Config Screen

---

src/Screens/PasswordRe.tsx

fix visual errors and validation of filled fields for the button.

fixing visual errors

---

src/Components/InputDestinatario.tsx
src/Firebase/db.tsx
src/Screens/History.tsx
src/Screens/Home.tsx
src/Screens/RetiroDetalles.tsx
src/Screens/TransferDetalles.tsx
src/Screens/Transferir.tsx
src/StackNavigation/MyStack.tsx

- Added modal for confirming a transference
- Added screen with transference information
- Fixed error messages from transfer screen
- Added icons to history screen buttons
- Fixed filter by date function
- Date pickers accept only past dates
History screen with filter by date

Add transfer confirmation screen, fix bugs on history screen

---

src/Components/MapView.tsx

.-Added initial Region by coordinates
.-We cant show the user location because the emulator location is in California 
.-When a user click a marker, is open in google maps

add initial region

---

src/Components/LoadingModal.tsx
src/Screens/Home.tsx
src/Screens/LogIn.tsx
src/Screens/SignUp.tsx

- When user logs in or signs up app shows a Loading modal while waiting for firebase response
- Errors from log in and sign up are handled 
- Alerts from log in and sign up are replaced for modals
When user log in or select log in with google app shows Loading, then takes user to home screen: 
When user insert an invalid password or email app shows error in modal:

Ccreate modal for loading and handle errors

---

src/Screens/SecurityScreen.tsx

A line of code was added to the security screen.

Error correction

---

src/Firebase/db.tsx
src/Screens/VirtualCardDetails.tsx
src/Screens/VirtualCreditRetiro.tsx
src/StackNavigation/MyStack.tsx

creation of the withdrawal screen with the virtual card and its function

 withdrawal with the virtual card and its function

---

__tests__/App.test.tsx
jest.config.js
package-lock.json
package.json
yarn.lock

.-Installed jest and react-ntaive testing library 
.-Installed ts-jest and types for testing

add testing library and dependecies

---

src/Components/MapView.tsx
src/Screens/AddContact.tsx
src/Screens/Config.tsx
src/Screens/DatosPersonales.tsx
src/Screens/DebitCardDetails.tsx
src/Screens/History.tsx
src/Screens/Home.tsx
src/Screens/MapScreen.tsx
src/Screens/MisTarjetas.tsx
src/Screens/PasswordRe.tsx
src/Screens/Retirar.tsx
src/Screens/SecurityScreen.tsx
src/Screens/SelectContact.tsx
src/Screens/Transferir.tsx
src/Screens/VirtualAddContact.tsx
src/Screens/VirtualCardDetails.tsx
src/Screens/VirtualTransferir.tsx
src/StackNavigation/MyStack.tsx

- All screens have a correct navigation between them
- all headers look the same now

Fix headers and added correct navigation between screens

---

src/Screens/Retirar.tsx
src/Screens/Transferir.tsx

Notifications were implemented when transferring and withdrawing money from the account.

notifications have been implemented.
